AWSTemplateFormatVersion: '2010-09-09'

Description: Cria o stack que implelenta a IAM Role necessaria para gerenciar
  recursos da AWS pelo Turbonomic. Este template cria acesso leitura e escrita.
  Atualizado em 06-2023

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Turbonomic
        Parameters:
          - TurboRoleName
          - TurboAccountID
    ParameterLabels:
      TurboRoleName:
        default: Turbonomic IAM Role Name
      TurboAccountID:
        default: Turbonomic Account ID

Parameters:
  TurboRoleName:
    Description: Nome do Turbonomic IAM Role que vai ser criado nas Accounts AWS. 
      Use somente caracteres alfanumericos e/ou +=,.@_-
    Type: String
    Default: 'Turbonomic_Cross_Account_Access'
  TurboAccountID:
    Description: Turbonomic Account ID Service Identifier
    Type: String
    Default: 'XXXXXXXXXXXXXXXXXX'

Resources:
  TurbonomicIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${TurboRoleName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: "accounts.google.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "accounts.google.com:sub": [!Ref TurboAccountID]
  TurbonomicCrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TurbonomicReadAndWritePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - autoscaling:CreateLaunchConfiguration
              - autoscaling:DeleteLaunchConfiguration
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:ResumeProcesses
              - autoscaling:SuspendProcesses
              - autoscaling:UpdateAutoScalingGroup
              - ce:GetReservationUtilization
              - ce:GetSavingsPlansCoverage
              - ce:GetSavingsPlansUtilization
              - ce:GetSavingsPlansUtilizationDetails
              - cloudwatch:GetMetricData
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
              - ec2:DeleteVolume
              - ec2:DescribeAccountAttributes
              - ec2:DescribeAddresses
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:DescribeRegions
              - ec2:DescribeReservedInstances
              - ec2:DescribeReservedInstancesModifications
              - ec2:DescribeReservedInstancesOfferings
              - ec2:DescribeSpotInstanceRequests
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeVolumes
              - ec2:DescribeVolumesModifications
              - ec2:DescribeVolumeStatus
              - ec2:ModifyInstanceAttribute
              - ec2:ModifyVolume
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:DescribeTags
              - elasticloadbalancing:DescribeInstanceHealth
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetHealth
              - iam:PassRole
              - iam:GetUser
              - KMS:CreateGrant
              - organizations:DescribeOrganization
              - organizations:ListAccounts
              - pi:GetResourceMetrics
              - rds:DescribeDBClusters
              - rds:DescribeDBInstances
              - rds:DescribeDBParameters
              - rds:DescribeOrderableDBInstanceOptions
              - rds:ListTagsForResource
              - rds:ModifyDBInstance
              - rds:StartDBInstance
              - rds:StopDBInstance
              - savingsplans:DescribeSavingsPlans
              - servicecatalog:DescribeProduct
              - servicecatalog:DescribeRecord
              - servicecatalog:ListLaunchPaths
              - servicecatalog:ProvisionProduct
              - servicecatalog:SearchProducts
            Effect: Allow
            Resource: '*'
      Roles: [!Ref TurbonomicIAMRole]
Outputs:
  RoleArn:
    Description: O ARN da Role do Turbonomic
    Value: !GetAtt [TurbonomicIAMRole, Arn]
  RoleName:
    Description: O nome da IAM Role que foi criado
    Value: !Ref TurbonomicIAMRole
