AWSTemplateFormatVersion: '2010-09-09'
Description: Cria um stack para implementacao da IAM Role necessaria para conectar o Turbonomic com a Master Account (Payer) e cria um bucket S3 para o billing export.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Turbonomic
        Parameters:
          - TurboRoleName
          - TenantId
          - TenantSvcAccount
          - S3Name
    ParameterLabels:
      TurboRoleName:
        default: Nome da IAM Role do Turbonomic
      TenantId:
        default: TenantId, entregue pela IBM
      TenantSvcAccount:
        default: TenantServiceAccount, entregue pela IBM.
      S3Name:
        default: Nome do S3 para o billing CUR, pode ser qualquer um.
Parameters:
  TurboRoleName:
    Description: Nome da IAM Role do Turbonomic que sera criada em sua account da AWS. 
      Use somente caracteres alfanumericos e/ou +=,.@_-
    Type: String
    Default: 'Turbonomic_Billing_Access'
  TenantId:
    Description: Nome do seu Tenant, entregue pela IBM.
    Type: String
    Default: 'coloque_seu_tenant_id'
  TenantSvcAccount:
    Description: Nome da sua Service Account, entregue pela IBM. 
    Type: String
    Default: 'coloque_seu_tenant_svc_account'
  S3Name:
    Description: Nome do S3 para o billing CUR, pode ser qualquer um.
    Type: String
    Default: turbonomic.nome.do.bucket.s3.turbonomic
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Criacao do bucket S3 que guardara o CUR do Turbonomic
    Properties:
      BucketName: !Sub ${S3Name}
      AccessControl: Private
  TurboOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - 06b25927c42a721631c1efd9431e648fa62e1e39
      Url: https://oidc.op1.openshiftapps.com/2c51blsaqa9gkjt0o9rt11mle8mmropu
  TurbonomicIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${TurboRoleName}
      AssumeRolePolicyDocument: 
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "${TurboOIDCProvider}"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "oidc.op1.openshiftapps.com/2c51blsaqa9gkjt0o9rt11mle8mmropu:sub": "system:serviceaccount:${TenantId}:${TenantSvcAccount}"
                        }
                    }
                }
            ]
          }
      Policies:  
        - PolicyName: TurbonomicBillingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - ce:GetReservationUtilization
                - ce:GetSavingsPlansCoverage
                - ce:GetSavingsPlansUtilization
                - ce:GetSavingsPlansUtilizationDetails
                - iam:GetUser
                - organizations:DescribeOrganization
                - organizations:ListAccounts
                - pricing:DescribeServices
                - pricing:GetAttributeValues
                - savingsplans:DescribeSavingsPlans
                - savingsplans:DescribeSavingsPlansOfferingRates
                Effect: Allow
                Resource: '*'
              - Action:
                - s3:GetBucketAcl
                - s3:GetObject
                Effect: Allow
                Resource:
                - arn:aws:s3:::turbonomic.${S3Name}.reports
                - arn:aws:s3:::turbonomic.${S3Name}.reports/*
Outputs:
  OIDCProvider:
    Description: The OIDC Provider
    Value: !Ref TurboOIDCProvider
  RoleArn:
    Description: The ARN of the Turbonomic IAM role
    Value: !GetAtt [TurbonomicIAMRole, Arn]
  RoleName:
    Description: The Name of the IAM role that was created
    Value: !Ref TurbonomicIAMRole
