AWSTemplateFormatVersion: '2010-09-09'
Description: Cria um stack para implementacao da IAM Role necessaria para conectar o Turbonomic com permissoes de execucao.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Turbonomic
        Parameters:
          - TurboRoleName
          - TenantId
          - TenantSvcAccount
    ParameterLabels:
      TurboRoleName:
        default: Nome da IAM Role do Turbonomic
      TenantId:
        default: TenantId, entregue pela IBM
      TenantSvcAccount:
        default: TenantServiceAccount, entregue pela IBM.
Parameters:
  TurboRoleName:
    Description: Nome da IAM Role do Turbonomic que sera criada em sua account da AWS. 
      Use somente caracteres alfanumericos e/ou +=,.@_-
    Type: String
    Default: 'Turbonomic_Access'
  TenantId:
    Description: Nome do seu Tenant, entregue pela IBM.
    Type: String
    Default: 'coloque_seu_tenant_id'
  TenantSvcAccount:
    Description: Nome da sua Service Account, entregue pela IBM. 
    Type: String
    Default: 'coloque_seu_tenant_svc_account'
Resources:
  TurboOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - 06b25927c42a721631c1efd9431e648fa62e1e39
      Url: https://oidc.op1.openshiftapps.com/2f785sojlpb85i7402pk3qogugim5nfb
  TurbonomicIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${TurboRoleName}
      AssumeRolePolicyDocument: 
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "${TurboOIDCProvider}"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "oidc.op1.openshiftapps.com/2f785sojlpb85i7402pk3qogugim5nfb:sub": "system:serviceaccount:${TenantId}:${TenantSvcAccount}"
                        }
                    }
                }
            ]
          }
      Policies:  
        - PolicyName: TurbonomicExecutePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - autoscaling:CreateLaunchConfiguration
                - autoscaling:DeleteLaunchConfiguration
                - autoscaling:DescribeAutoScalingGroups
                - autoscaling:DescribeLaunchConfigurations
                - autoscaling:ResumeProcesses
                - autoscaling:SuspendProcesses
                - autoscaling:UpdateAutoScalingGroup
                - autoscaling:SetDesiredCapacity
                - autoscaling:TerminateInstanceInAutoScalingGroup
                - ce:GetReservationUtilization
                - ce:GetSavingsPlansCoverage
                - ce:GetSavingsPlansUtilization
                - ce:GetSavingsPlansUtilizationDetails
                - cloudwatch:GetMetricData
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
                - cloudtrail:LookupEvents
                - ec2:DescribeAccountAttributes
                - ec2:DescribeAddresses
                - ec2:DescribeAvailabilityZones
                - ec2:DescribeImages
                - ec2:DescribeInstances
                - ec2:DescribeInstanceTypes
                - ec2:DescribeInstanceTypeOfferings
                - ec2:DescribeInstanceStatus
                - ec2:DescribeRegions
                - ec2:DescribeReservedInstances
                - ec2:DescribeReservedInstancesModifications
                - ec2:DescribeReservedInstancesOfferings
                - ec2:DescribeSpotInstanceRequests
                - ec2:DescribeSpotPriceHistory
                - ec2:DescribeVolumes
                - ec2:DescribeVolumesModifications
                - ec2:DescribeVolumeStatus
                - ec2:ModifyInstanceAttribute
                - ec2:ModifyVolume
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:DeleteVolume
                - ec2:DescribeTags
                - elasticloadbalancing:DescribeInstanceHealth
                - elasticloadbalancing:DescribeLoadBalancers
                - elasticloadbalancing:DescribeTargetGroups
                - elasticloadbalancing:DescribeTargetHealth
                - iam:PassRole
                - iam:GetUser
                - KMS:CreateGrant
                - organizations:DescribeOrganization
                - organizations:ListAccounts
                - pi:GetResourceMetrics
                - pi:ListAvailableResourceMetrics
                - rds:DescribeDBClusters
                - rds:DescribeDBInstances
                - rds:DescribeDBParameters
                - rds:DescribeOrderableDBInstanceOptions
                - rds:DescribeReservedDBInstances
                - rds:ListTagsForResource
                - rds:ModifyDBInstance
                - rds:StartDBInstance
                - rds:StopDBInstance
                - savingsplans:DescribeSavingsPlans
                - savingsplans:DescribeSavingsPlansOfferingRates
                - servicecatalog:DescribeProduct
                - servicecatalog:DescribeRecord
                - servicecatalog:ListLaunchPaths
                - servicecatalog:ProvisionProduct
                - servicecatalog:SearchProducts
                Effect: Allow
                Resource: '*'
Outputs:
  OIDCProvider:
    Description: The OIDC Provider
    Value: !Ref TurboOIDCProvider
  RoleArn:
    Description: The ARN of the Turbonomic IAM role
    Value: !GetAtt [TurbonomicIAMRole, Arn]
  RoleName:
    Description: The Name of the IAM role that was created
    Value: !Ref TurbonomicIAMRole
